# Generated by Django 6.1 on 2026-09-18 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0004_alter_incident_table_alter_incidentcategory_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_details', models.TextField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUBMITTED', max_length=30)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='incidents.incident')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
