# Generated by Django 6.1 on 2026-09-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_remove_incident_id_remove_incident_watchman_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incident',
            table='incidents',
        ),
        migrations.AlterModelTable(
            name='incidentcategory',
            table='incident_categories',
        ),
    ]
